### ISSUE TITLE
Can version 3.35 be used?

### ISSUE THREAD

**Issue by TFGH164** [Macumbafeh/BlizzFader#2]

**Comment by Macumbafeh** [comment]
Afaik it work on 3.3.5 yes. 

I don't remember if i used it on 3.3.5...

**Comment by TFGH164** [comment]
I found in the 3.35 test that Enemy fade out cannot be used, but everything else is fine. Can you fix it?

**Comment by Macumbafeh** [comment]
i just tested it, and the only think which doesn't work well is the Deazone border.

The /bf command doesn't work but that's normal. i need to change InterfaceOptionsFrame_OpenToFrame to InterfaceOptionsFrame_OpenToCategory

Otherwise the Enemy fade out worked. i tested it with a rogue.

![image](https://github.com/user-attachments/assets/2f2e6e3e-c32f-41aa-a44d-8388b89cfdcf)

![image](https://github.com/user-attachments/assets/362cf742-0803-4bcf-8aef-ce77d90a18b4)


Used with Throw ability.


I created a new branch for 3.3.5 : https://github.com/Macumbafeh/BlizzFader/tree/3.3.5

**Comment by TFGH164** [comment]
It can work normally now. Thank you very much! Many of your addons are great, it would be even better if they could all support 3.35. For example, XiconPlateBuffs, I think it looks better than platebuffs! Thank you for your contribution no matter what!

**Comment by TFGH164** [comment]
There is another request. Can you also develop an addons about the arena? It can change the enemy's name to the number 123. When we enter the arena, the enemy's name automatically changes to 1, 2, 3, 4, and 5. It also adds options for size, color, and position. It can support 3.4.3, 3.35. Here are some reference materials: https://github.com/Poli93/ArenaNumbers (It can only display 1, 2, 3, not 4, 5, and all names will become huge when leaving the arena, without automatic reset) Another information: https://github.com/Macumbatbc/ArenaNumberAsName (It does not have an option to adjust its position, which means it will be blocked by platebuffs and will not work in 3.35)

**Comment by Macumbafeh** [comment]
> It can work normally now. Thank you very much! Many of your addons are great, it would be even better if they could all support 3.35. For example, XiconPlateBuffs, I think it looks better than platebuffs! Thank you for your contribution no matter what!

It's not my addon, But it was inspired by Platebuffs addon. You can ask Xicon to update it on his github

**Comment by Macumbafeh** [comment]
> There is another request. Can you also develop an addons about the arena? It can change the enemy's name to the number 123. When we enter the arena, the enemy's name automatically changes to 1, 2, 3, 4, and 5. It also adds options for size, color, and position. It can support 3.4.3, 3.35. Here are some reference materials: https://github.com/Poli93/ArenaNumbers (It can only display 1, 2, 3, not 4, 5, and all names will become huge when leaving the arena, without automatic reset) Another information: https://github.com/Macumbatbc/ArenaNumberAsName (It does not have an option to adjust its position, which means it will be blocked by platebuffs and will not work in 3.35)

Sadly i don't play wow anymore. It will be difficult to test it.

**Comment by Macumbafeh** [comment]
> There is another request. Can you also develop an addons about the arena? It can change the enemy's name to the number 123. When we enter the arena, the enemy's name automatically changes to 1, 2, 3, 4, and 5. It also adds options for size, color, and position. It can support 3.4.3, 3.35. Here are some reference materials: https://github.com/Poli93/ArenaNumbers (It can only display 1, 2, 3, not 4, 5, and all names will become huge when leaving the arena, without automatic reset) Another information: https://github.com/Macumbatbc/ArenaNumberAsName (It does not have an option to adjust its position, which means it will be blocked by platebuffs and will not work in 3.35)

I forked it and checked it fastly, i added a reset feature, no idea if it will work properly...
https://github.com/Macumbafeh/ArenaNumbers
