### ISSUE TITLE
errors when targeting

### ISSUE THREAD

**Issue by Zergei** [Macumbafeh/BlizzFader#3]
1x BlizzFader\BlizzFader.lua:1484: IsSpellInRange(): Invalid spell slot
BlizzFader\BlizzFader.lua:1484: in function <BlizzFader\BlizzFader.lua:874>
BlizzFader\BlizzFader.lua:1515: in function <BlizzFader\BlizzFader.lua:1510>

Locals:
(for index) = 5
(for limit) = 5
(for step) = 1
i = 5
frame = TargetFrame {
 debuffs = TargetFrameDebuffs {}
 portrait = TargetFramePortrait {}
 showThreat = true
 raidTargetIcon = TargetFrameTextureFrameRaidTargetIcon {}
 highLevelTexture = TargetFrameTextureFrameHighLevelTexture {}
 healAbsorbBarRightShadow = TargetFrameHealAbsorbBarRightShadow {}
 healAbsorbBarLeftShadow = TargetFrameHealAbsorbBarLeftShadow {}
 totalAbsorbBarOverlay = TargetFrameTotalAbsorbBarOverlay {}
 elapsed = 0
 showAuraCount = true
 showLeader = true
 healthbar = TargetFrameHealthBar {}
 pvpIcon = TargetFrameTextureFramePVPIcon {}
 deadText = TargetFrameTextureFrameDeadText {}
 MALockPointHook = true
 myHealPredictionBar = TargetFrameFrameMyHealPredictionBar {}
 noTextPrefix = true
 SetPoint = <function> defined =[C]:-1
 auraRows = 0
 buffs = TargetFrameBuffs {}
 nameBackground = TargetFrameNameBackground {}
 showLevel = true
 levelText = TargetFrameTextureFrameLevelText {}
 MAHooked = true
 leaderIcon = TargetFrameTextureFrameLeaderIcon {}
 healAbsorbBar = TargetFrameHealAbsorbBar {}
 myManaCostPredictionBar = TargetFrameFrameManaCostPredictionBar {}
 opt = <table> {}
 statusSign = -1
 unit = "target"
 showPVP = true
 maxDebuffs = 8
 maxBuffs = 16
 borderTexture = TargetFrameTextureFrameTexture {}
 totalAbsorbBar = TargetFrameTotalAbsorbBar {}
 showPortrait = true
 TOT_AURA_ROW_WIDTH = 101
 overHealAbsorbGlow = TargetFrameOverHealAbsorbGlow {}
 statusCounter = 0
 overAbsorbGlow = TargetFrameFrameOverAbsorbGlow {}
 threatIndicator = TargetFrameFlash {}
 manabar = TargetFrameManaBar {}
 totFrame = TargetFrameToT {}
 unitHPPercent = 1
 OnEvent = <function> @ Interface\FrameXML\TargetFrame.lua:137:
 MAPoint = <table> {}
 spellbar = TargetFrameSpellBar {}
 menu = <function> @ Interface\FrameXML\TargetFrame.lua:87:
 showClassification = true
 0 = <userdata>
 threatNumericIndicator = TargetFrameNumericalThreat {}
 otherHealPredictionBar = TargetFrameFrameOtherHealPredictionBar {}
 name = TargetFrameTextureFrameName {}
}
unit = "target"
inRange = true
frameCount = 5
frameList = <table> {
 1 = PartyMemberFrame1 {}
 2 = PartyMemberFrame2 {}
 3 = PartyMemberFrame3 {}
 4 = PartyMemberFrame4 {}
 5 = TargetFrame {}
}
unitList = <table> {
 1 = "party1"
 2 = "party2"
 3 = "party3"
 4 = "party4"
 5 = "target"
}

  ---

**Comment by Macumbafeh** [comment]
Hello, which class are you playing. 
Also test without any other addon.
I guess you use 3.3.5 client?

Edit : i updated the libs. try again with the new version.

**Comment by Zergei** [comment]
> Hello, which class are you playing. Also test without any other addon. I guess you use 3.3.5 client?
> 
> Edit : i updated the libs. try again with the new version.

now it works ty for the update
